{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os, re, requests, tarfile\n",
    "import random, shutil\n",
    "\n",
    "word_map = {}\n",
    "with open(\"words.txt\", \"r\") as words:\n",
    "    for line in words.readlines():\n",
    "        lines_split = line.split(\"\\t\")\n",
    "        word_map[lines_split[0]] = lines_split[1].replace(\"\\n\", \"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_images(id, n):\n",
    "    folder_path = f\"image_net\\\\extracted_{id}\"\n",
    "    \n",
    "    for _ in range(min(n, len(os.listdir(folder_path))-1)):\n",
    "        folder_size = len(os.listdir(folder_path)) - 1\n",
    "        rnd_idx = random.randint(0, folder_size)\n",
    "\n",
    "        rnd_image = os.listdir(folder_path)[rnd_idx]\n",
    "\n",
    "        if not os.path.exists(f\"image_net\\\\{id}\"):\n",
    "            os.mkdir(f\"image_net\\\\{id}\")\n",
    "\n",
    "        os.replace(f\"{folder_path}\\\\{rnd_image}\", f\"image_net\\\\{id}\\\\{rnd_image}\")\n",
    "    \n",
    "    shutil.rmtree(folder_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "7426\n",
      "82115\n",
      "74689\n"
     ]
    }
   ],
   "source": [
    "non_downloadable_ids = set()\n",
    "with open(\"image_net\\\\non_downloadable_synsets.txt\", \"r\") as non_downloadable_synsets:\n",
    "    for line in non_downloadable_synsets.readlines():\n",
    "        non_downloadable_ids.add(line.replace(\"\\n\", \"\"))\n",
    "    \n",
    "print(len(non_downloadable_ids))\n",
    "print(len(word_map.keys()))\n",
    "\n",
    "downloadable_ids = sorted(set(word_map.keys()).difference(non_downloadable_ids))\n",
    "print(len(downloadable_ids))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[36m11\u001b[0m Downloading n00006024 : heterotroph\n",
      "\u001b[36m2185\u001b[0m Downloading n00443375 : dead-man's float, prone float\n",
      "\u001b[36m2189\u001b[0m Downloading n00443917 : gainer, full gainer\n",
      "\u001b[36m6815\u001b[0m Downloading n01333483 : vesiculovirus\n",
      "\u001b[36m7299\u001b[0m Downloading n01429172 : Ostariophysi, order Ostariophysi\n",
      "\u001b[36m8049\u001b[0m Downloading n01580772 : New World jay\n",
      "\u001b[36m8094\u001b[0m Downloading n01588002 : brown thrasher, brown thrush, Toxostoma rufums\n",
      "\u001b[36m8095\u001b[0m \u001b[31mCan't download n01588172 : Xenicidae, family Xenicidae, Acanthisittidae, family Acanthisittidae\u001b[0m\n",
      "\u001b[36m8096\u001b[0m Downloading n01588431 : New Zealand wren\n",
      "\u001b[36m8097\u001b[0m \u001b[31mCan't download n01588589 : Xenicus, genus Xenicus\u001b[0m\n",
      "\u001b[36m8098\u001b[0m Downloading n01588725 : rock wren, Xenicus gilviventris\n",
      "\u001b[36m8099\u001b[0m \u001b[31mCan't download n01588858 : Acanthisitta, genus Acanthisitta\u001b[0m\n",
      "\u001b[36m8100\u001b[0m Downloading n01588996 : rifleman bird, Acanthisitta chloris\n",
      "\u001b[36m8101\u001b[0m \u001b[31mCan't download n01589125 : Certhiidae, family Certhiidae\u001b[0m\n",
      "\u001b[36m8102\u001b[0m Downloading n01589286 : creeper, tree creeper\n",
      "\u001b[36m8103\u001b[0m \u001b[31mCan't download n01589582 : Certhia, genus Certhia\u001b[0m\n",
      "\u001b[36m8104\u001b[0m Downloading n01589718 : brown creeper, American creeper, Certhia americana\n",
      "\u001b[36m8105\u001b[0m Downloading n01589893 : European creeper, Certhia familiaris\n",
      "\u001b[36m8106\u001b[0m \u001b[31mCan't download n01590042 : Tichodroma, genus Tichodroma\u001b[0m\n",
      "\u001b[36m8107\u001b[0m Downloading n01590220 : wall creeper, tichodrome, Tichodroma muriaria\n",
      "\u001b[36m8108\u001b[0m \u001b[31mCan't download n01590443 : Sittidae, family Sittidae\u001b[0m\n",
      "\u001b[36m8109\u001b[0m \u001b[31mCan't download n01590583 : nuthatch, nutcracker\u001b[0m\n",
      "\u001b[36m8110\u001b[0m \u001b[31mCan't download n01590837 : Sitta, genus Sitta\u001b[0m\n",
      "\u001b[36m8111\u001b[0m Downloading n01591005 : European nuthatch, Sitta europaea\n",
      "\u001b[36m8112\u001b[0m Downloading n01591123 : red-breasted nuthatch, Sitta canadensis\n",
      "\u001b[36m8113\u001b[0m Downloading n01591301 : white-breasted nuthatch, Sitta carolinensis\n",
      "\u001b[36m8114\u001b[0m \u001b[31mCan't download n01591490 : Paridae, family Paridae\u001b[0m\n",
      "\u001b[36m8115\u001b[0m Downloading n01591697 : titmouse, tit\n",
      "\u001b[36m8116\u001b[0m \u001b[31mCan't download n01591910 : Parus, genus Parus\u001b[0m\n",
      "\u001b[36m8117\u001b[0m Downloading n01592084 : chickadee\n",
      "\u001b[36m8118\u001b[0m Downloading n01592257 : black-capped chickadee, blackcap, Parus atricapillus\n",
      "\u001b[36m8119\u001b[0m Downloading n01592387 : tufted titmouse, Parus bicolor\n",
      "\u001b[36m8120\u001b[0m Downloading n01592540 : Carolina chickadee, Parus carolinensis\n",
      "\u001b[36m8121\u001b[0m Downloading n01592694 : blue tit, tomtit, Parus caeruleus\n",
      "\u001b[36m8122\u001b[0m \u001b[31mCan't download n01592892 : Psaltriparus, genus Psaltriparus\u001b[0m\n",
      "\u001b[36m8123\u001b[0m Downloading n01593028 : bushtit, bush tit\n",
      "\u001b[36m8124\u001b[0m \u001b[31mCan't download n01593156 : Chamaea, genus Chamaea\u001b[0m\n",
      "\u001b[36m8125\u001b[0m Downloading n01593282 : wren-tit, Chamaea fasciata\n",
      "\u001b[36m8126\u001b[0m \u001b[31mCan't download n01593423 : Auriparus, genus Auriparus\u001b[0m\n",
      "\u001b[36m8127\u001b[0m Downloading n01593553 : verdin, Auriparus flaviceps\n",
      "\u001b[36m8128\u001b[0m \u001b[31mCan't download n01593705 : Irenidae, family Irenidae\u001b[0m\n",
      "\u001b[36m8129\u001b[0m \u001b[31mCan't download n01593857 : Irena, genus Irena\u001b[0m\n",
      "\u001b[36m8130\u001b[0m Downloading n01594004 : fairy bluebird, bluebird\n",
      "\u001b[36m8131\u001b[0m \u001b[31mCan't download n01594157 : Hirundinidae, family Hirundinidae\u001b[0m\n",
      "\u001b[36m8132\u001b[0m Downloading n01594372 : swallow\n",
      "\u001b[36m8133\u001b[0m \u001b[31mCan't download n01594611 : Hirundo, genus Hirundo\u001b[0m\n",
      "\u001b[36m8134\u001b[0m Downloading n01594787 : barn swallow, chimney swallow, Hirundo rustica\n",
      "\u001b[36m8135\u001b[0m Downloading n01594968 : cliff swallow, Hirundo pyrrhonota\n",
      "\u001b[36m8136\u001b[0m Downloading n01595168 : tree swallow, tree martin, Hirundo nigricans\n",
      "\u001b[36m8137\u001b[0m \u001b[31mCan't download n01595330 : Iridoprocne, genus Iridoprocne\u001b[0m\n",
      "\u001b[36m8138\u001b[0m Downloading n01595450 : white-bellied swallow, tree swallow, Iridoprocne bicolor\n",
      "\u001b[36m8139\u001b[0m Downloading n01595624 : martin\n",
      "\u001b[36m8140\u001b[0m \u001b[31mCan't download n01595841 : Delichon, genus Delichon\u001b[0m\n",
      "\u001b[36m8141\u001b[0m Downloading n01595974 : house martin, Delichon urbica\n",
      "\u001b[36m8142\u001b[0m \u001b[31mCan't download n01596142 : Riparia, genus Riparia\u001b[0m\n",
      "\u001b[36m8143\u001b[0m Downloading n01596273 : bank martin, bank swallow, sand martin, Riparia riparia\n",
      "\u001b[36m8144\u001b[0m \u001b[31mCan't download n01596479 : Progne, genus Progne\u001b[0m\n",
      "\u001b[36m8145\u001b[0m (\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))\n",
      "\u001b[36m8146\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01596761.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C47F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8147\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01596887.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8148\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01597022.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4D30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8149\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01597194.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C42E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8150\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01597336.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8151\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01597551.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4C10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8152\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01597737.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C46D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8153\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01597906.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C46D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8154\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01598074.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C46D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8155\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01598271.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8156\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01598432.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8157\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01598588.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8158\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01598820.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4AC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8159\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01598988.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8160\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01599159.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C44F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8161\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01599269.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4D30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8162\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01599388.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8163\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01599556.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8164\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01599741.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8165\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01599919.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4AC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8166\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01600085.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8167\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01600197.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C45E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8168\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01600341.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C47F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8169\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01600480.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C46D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8170\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01600657.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8171\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01600909.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4460>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8172\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01601068.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4AC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8173\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01601268.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C44F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8174\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01601410.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C46D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8175\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01601550.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4D90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8176\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01601694.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C47F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8177\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01601919.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8178\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01602080.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4460>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8179\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01602209.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4AC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8180\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01602353.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C44F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8181\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01602506.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C44F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8182\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01602630.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C44F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8183\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01602832.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C44F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8184\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01603000.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C44F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8185\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01603152.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C44F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8186\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01603316.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C44F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8187\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01603478.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8188\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01603600.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8189\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01603812.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8190\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01603953.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8191\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01604123.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A8B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8192\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01604330.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8193\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01604625.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8194\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01604968.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8195\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01605119.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8196\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01605630.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8197\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01606097.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8198\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01606177.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8199\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01606335.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8200\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01606522.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8201\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01606672.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8202\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01606809.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8203\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01606978.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8204\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01607103.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8205\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01607309.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8206\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01607429.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8207\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01607600.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8208\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01607812.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8209\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01607962.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8210\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01608086.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8211\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01608265.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8212\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01608432.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8213\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01608685.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8214\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01608814.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8215\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01608934.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8216\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01609062.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8217\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01609236.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8218\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01609391.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8219\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01609549.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8220\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01609751.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8221\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01609956.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8222\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01610100.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8223\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01610226.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8224\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01610426.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8225\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01610552.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C46D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8226\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01610758.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C46D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8227\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01610955.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8228\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01611252.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8229\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01611472.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8230\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01611674.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8231\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01611800.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8232\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01611969.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8233\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01612122.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8234\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01612275.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8235\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01612476.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C42E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8236\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01612628.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C48E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8237\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01612803.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C48E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8238\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01612955.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C48E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8239\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01613177.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C48E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8240\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01613294.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8241\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01613615.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8242\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01613807.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8243\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01613909.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8244\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01614038.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8245\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01614195.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8246\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01614343.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4A60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8247\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01614556.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8248\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01614690.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8249\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01614769.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8250\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01614925.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8251\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01615121.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C4100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8252\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01615303.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8253\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01615458.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8254\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01615703.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8255\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01615825.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6AFD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8256\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01615949.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8257\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01616086.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8258\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01616318.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8259\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01616551.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8260\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01616764.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466D9C48E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8261\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01616970.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8262\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01617095.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8263\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01617289.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8264\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01617443.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8265\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01617633.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8266\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01617766.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8267\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01617949.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8268\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01618082.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8269\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01618220.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8270\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01618356.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8271\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01618503.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8272\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01618671.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8273\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01618922.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8274\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01619152.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8275\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01619310.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8276\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01619536.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8277\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01619675.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8278\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01619835.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8279\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01620003.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8280\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01620135.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8281\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01620282.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8282\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01620414.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8283\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01620575.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8284\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01620735.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8285\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01620967.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8286\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01621127.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8287\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01621635.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8288\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01621714.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8289\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01621994.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8290\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01622120.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8291\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01622230.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8292\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01622352.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8293\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01622483.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8294\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01622596.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8295\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01622779.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8296\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01622959.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8297\u001b[0m (\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))\n",
      "\u001b[36m8298\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01623284.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6AFD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8299\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01623425.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A8B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8300\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01623615.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8301\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01623706.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8302\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01623880.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8303\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01624115.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6AFD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8304\u001b[0m HTTPSConnectionPool(host='image-net.org', port=443): Max retries exceeded with url: /data/winter21_whole/n01624212.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001466DD6A730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "\u001b[36m8305\u001b[0m "
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_3652/682214560.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      8\u001b[0m     \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34mf\"\\u001b[36m{list(word_map.keys()).index(id)}\\u001b[0m \"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mend\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m''\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      9\u001b[0m     \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 10\u001b[1;33m         \u001b[0mget_request\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mrequests\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34mf\"https://image-net.org/data/winter21_whole/{id}.tar\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     11\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mget_request\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstatus_code\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;36m200\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     12\u001b[0m             \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34mf\"Downloading {id} : {word_map[id]}\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\requests\\api.py\u001b[0m in \u001b[0;36mget\u001b[1;34m(url, params, **kwargs)\u001b[0m\n\u001b[0;32m     73\u001b[0m     \"\"\"\n\u001b[0;32m     74\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 75\u001b[1;33m     \u001b[1;32mreturn\u001b[0m \u001b[0mrequest\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'get'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mparams\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mparams\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     76\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     77\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\requests\\api.py\u001b[0m in \u001b[0;36mrequest\u001b[1;34m(method, url, **kwargs)\u001b[0m\n\u001b[0;32m     59\u001b[0m     \u001b[1;31m# cases, and look like a memory leak in others.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     60\u001b[0m     \u001b[1;32mwith\u001b[0m \u001b[0msessions\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mSession\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0msession\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 61\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0msession\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrequest\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmethod\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mmethod\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0murl\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     62\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     63\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\requests\\sessions.py\u001b[0m in \u001b[0;36mrequest\u001b[1;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[0;32m    527\u001b[0m         }\n\u001b[0;32m    528\u001b[0m         \u001b[0msend_kwargs\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msettings\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 529\u001b[1;33m         \u001b[0mresp\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mprep\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0msend_kwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    530\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    531\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mresp\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\requests\\sessions.py\u001b[0m in \u001b[0;36msend\u001b[1;34m(self, request, **kwargs)\u001b[0m\n\u001b[0;32m    643\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    644\u001b[0m         \u001b[1;31m# Send the request\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 645\u001b[1;33m         \u001b[0mr\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0madapter\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrequest\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    646\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    647\u001b[0m         \u001b[1;31m# Total elapsed time of the request (approximately)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\requests\\adapters.py\u001b[0m in \u001b[0;36msend\u001b[1;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[0;32m    438\u001b[0m         \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    439\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mchunked\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 440\u001b[1;33m                 resp = conn.urlopen(\n\u001b[0m\u001b[0;32m    441\u001b[0m                     \u001b[0mmethod\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mrequest\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mmethod\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    442\u001b[0m                     \u001b[0murl\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\urllib3\\connectionpool.py\u001b[0m in \u001b[0;36murlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[0;32m    701\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    702\u001b[0m             \u001b[1;31m# Make the request on the httplib connection object.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 703\u001b[1;33m             httplib_response = self._make_request(\n\u001b[0m\u001b[0;32m    704\u001b[0m                 \u001b[0mconn\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    705\u001b[0m                 \u001b[0mmethod\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\urllib3\\connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[1;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[0;32m    384\u001b[0m         \u001b[1;31m# Trigger any extra validation we need to do.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    385\u001b[0m         \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 386\u001b[1;33m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_validate_conn\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mconn\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    387\u001b[0m         \u001b[1;32mexcept\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mSocketTimeout\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mBaseSSLError\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    388\u001b[0m             \u001b[1;31m# Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\urllib3\\connectionpool.py\u001b[0m in \u001b[0;36m_validate_conn\u001b[1;34m(self, conn)\u001b[0m\n\u001b[0;32m   1038\u001b[0m         \u001b[1;31m# Force connect early to allow us to validate the connection.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1039\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mconn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m\"sock\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m  \u001b[1;31m# AppEngine might not have  `.sock`\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1040\u001b[1;33m             \u001b[0mconn\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1041\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1042\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mconn\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mis_verified\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\urllib3\\connection.py\u001b[0m in \u001b[0;36mconnect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    414\u001b[0m             \u001b[0mcontext\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mload_default_certs\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    415\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 416\u001b[1;33m         self.sock = ssl_wrap_socket(\n\u001b[0m\u001b[0;32m    417\u001b[0m             \u001b[0msock\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mconn\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    418\u001b[0m             \u001b[0mkeyfile\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mkey_file\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\urllib3\\util\\ssl_.py\u001b[0m in \u001b[0;36mssl_wrap_socket\u001b[1;34m(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)\u001b[0m\n\u001b[0;32m    447\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    448\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0msend_sni\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 449\u001b[1;33m         ssl_sock = _ssl_wrap_socket_impl(\n\u001b[0m\u001b[0;32m    450\u001b[0m             \u001b[0msock\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mcontext\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtls_in_tls\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mserver_hostname\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mserver_hostname\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    451\u001b[0m         )\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\urllib3\\util\\ssl_.py\u001b[0m in \u001b[0;36m_ssl_wrap_socket_impl\u001b[1;34m(sock, ssl_context, tls_in_tls, server_hostname)\u001b[0m\n\u001b[0;32m    491\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    492\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mserver_hostname\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 493\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mssl_context\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mwrap_socket\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msock\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mserver_hostname\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mserver_hostname\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    494\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    495\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mssl_context\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mwrap_socket\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msock\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\ssl.py\u001b[0m in \u001b[0;36mwrap_socket\u001b[1;34m(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)\u001b[0m\n\u001b[0;32m    498\u001b[0m         \u001b[1;31m# SSLSocket class handles server_hostname encoding before it calls\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    499\u001b[0m         \u001b[1;31m# ctx._wrap_socket()\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 500\u001b[1;33m         return self.sslsocket_class._create(\n\u001b[0m\u001b[0;32m    501\u001b[0m             \u001b[0msock\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0msock\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    502\u001b[0m             \u001b[0mserver_side\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mserver_side\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\ssl.py\u001b[0m in \u001b[0;36m_create\u001b[1;34m(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)\u001b[0m\n\u001b[0;32m   1038\u001b[0m                         \u001b[1;31m# non-blocking\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1039\u001b[0m                         \u001b[1;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"do_handshake_on_connect should not be specified for non-blocking sockets\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1040\u001b[1;33m                     \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdo_handshake\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1041\u001b[0m             \u001b[1;32mexcept\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mOSError\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mValueError\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1042\u001b[0m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mclose\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\jovin\\AppData\\Local\\Programs\\Python\\Python39\\lib\\ssl.py\u001b[0m in \u001b[0;36mdo_handshake\u001b[1;34m(self, block)\u001b[0m\n\u001b[0;32m   1307\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mtimeout\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;36m0.0\u001b[0m \u001b[1;32mand\u001b[0m \u001b[0mblock\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1308\u001b[0m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msettimeout\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;32mNone\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1309\u001b[1;33m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_sslobj\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdo_handshake\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1310\u001b[0m         \u001b[1;32mfinally\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1311\u001b[0m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msettimeout\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "if not os.path.exists(\"image_net\"):\n",
    "    os.mkdir(\"image_net\")\n",
    "\n",
    "for id in downloadable_ids:\n",
    "    if os.path.exists(f\"image_net\\\\{id}\"):\n",
    "        continue\n",
    "\n",
    "    print(f\"\\u001b[36m{list(word_map.keys()).index(id)}\\u001b[0m \", end='')\n",
    "    try:\n",
    "        get_request = requests.get(f\"https://image-net.org/data/winter21_whole/{id}.tar\")\n",
    "        if get_request.status_code == 200:\n",
    "            print(f\"Downloading {id} : {word_map[id]}\")\n",
    "            with open(f\"image_net\\\\compressed_{id}.tar\", \"wb\") as compressed_id:\n",
    "                compressed_id.write(get_request.content)\n",
    "            \n",
    "            with tarfile.open(f\"image_net\\\\compressed_{id}.tar\") as compressed_tar:\n",
    "                compressed_tar.extractall(f\"image_net\\\\extracted_{id}\")\n",
    "\n",
    "            os.remove(f\"image_net\\\\compressed_{id}.tar\")\n",
    "\n",
    "            # Extract 5 random images from the synset.\n",
    "            extract_images(id, 5)\n",
    "        else:\n",
    "            print(f\"\\u001b[31mCan't download {id} : {word_map[id]}\\u001b[0m\")\n",
    "            with open(\"image_net\\\\non_downloadable_synsets.txt\", \"a\") as non_downloadable_synsets:\n",
    "                non_downloadable_synsets.write(f\"{id}\\n\")\n",
    "    except Exception as e:\n",
    "        print(e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# delete excess files\n",
    "for id in downloadable_ids:\n",
    "    folder_path = f\"image_net\\\\{id}\"\n",
    "    folder_size = len(os.listdir(folder_path))\n",
    "\n",
    "    while folder_size > 5:\n",
    "        rnd_idx = random.randint(0, folder_size-1)\n",
    "        print(os.listdir(folder_path)[rnd_idx])\n",
    "        # os.remove(os.listdir(folder_path)[rnd_idx])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open(\"downloaded_index-word.txt\", \"w\") as index_word_file:\n",
    "    for id in os.listdir(\"image_net\"):\n",
    "        if id in word_map:\n",
    "            index_word_file.write(f\"{id}\\t{word_map[id]}\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "# SORT THE NON-DOWNLOADABLES\n",
    "non_downloadable_ids = set()\n",
    "with open(\"image_net\\\\non_downloadable_synsets.txt\", \"r\") as non_downloadable_synsets:\n",
    "    for line in non_downloadable_synsets.readlines():\n",
    "        non_downloadable_ids.add(line.replace(\"\\n\", \"\"))\n",
    "\n",
    "with open(\"image_net\\\\non_downloadable_synsets.txt\", \"w\") as non_downloadable_synsets:\n",
    "    non_downloadable_ids = sorted(non_downloadable_ids)\n",
    "    for id in non_downloadable_ids:\n",
    "        non_downloadable_synsets.write(f\"{id}\\n\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.9.2 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.2"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "67f71cad8bb00401cc70b562b4176ce68c52a737baafa4e0e01596c30c42a5b8"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
